################################################################################
## variables
################################################################################

# explicitly defines to avoid confusion if inherited from environment
SHELL         := /bin/sh

# defines the chraracter that deonte the start of a recipie line
.RECIPEPREFIX := \t

PROJECT       := $(shell basename $(CURDIR))
GOAL          := bin/$(PROJECT)

SRCDIR        := src
BLDDIR        := build
DEPDIR        := .d

SRC           := $(wildcard $(SRCDIR)/*.cpp)
OBJ           := $(patsubst $(SRCDIR)/%,$(BLDDIR)/%,$(SRC:.cpp=.o))
DEP           := $(patsubst $(SRCDIR)/%,$(DEPDIR)/%,$(SRC:.cpp=.d))

CPP            = $(shell wx-config --cxx)

DEPFLAGS       = -MT $@ -MMD -MP -MF $(DEPDIR)/$*.Td
WFLAGS        := -W -Wall -Wextra -Werror -Wfatal-errors
CPPFLAGS       = -std=gnu++11 `wx-config --cxxflags`
INC           := -I include
INC           += -I /opt/local/include
#INC           += -I /usr/include
LDFLAGS       := -L /opt/local/lib
#LDFLAGS       += -L /usr/lib/x86_64-linux-gnu

LDLIBS   = `wx-config --libs core,base,propgrid,adv` # added core,base,propgrid
#LDLIBS  += -lwx_osx_cocoau_propgrid-3.0.0.2.0 # or add core,base,propgrid above
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Linux)
    LDLIBS  += -lboost_system
    LDLIBS  += -lboost_filesystem
    LDLIBS  += -lboost_serialization
    LDLIBS  += -lboost_thread
endif
ifeq ($(UNAME_S),Darwin)
    LDLIBS  += -lboost_system-mt
    LDLIBS  += -lboost_filesystem-mt
    LDLIBS  += -lboost_serialization-mt
    LDLIBS  += -lboost_thread-mt
endif

Compile        = $(CPP) $(DEPFLAGS) $(CPPFLAGS) $(INC) -c
Link           = $(CPP) $(LDFLAGS) $(LDLIBS)
OUTPUT_OPTION  = -o $@
POSTCOMPILE    = mv -f $(DEPDIR)/$*.Td $(DEPDIR)/$*.d

################################################################################
## rules
################################################################################

$(GOAL): $(OBJ)
	@echo "Linking..."
	$(Link) $(OUTPUT_OPTION) $^

$(BLDDIR)/%.o: $(SRCDIR)/%.cpp $(DEPDIR)/%.d | $(DEPDIR)
	@echo "Compiling..."
	$(Compile) $(OUTPUT_OPTION) $<
	$(POSTCOMPILE)

$(DEPDIR):
	@mkdir $@

$(DEPDIR)/%.d: ;

.PRECIOUS: $(DEPDIR)/%.d

-include $(DEP)

.PHONY: clean test info

clean:
	@echo " Cleaning..."
	rm -f $(BLDDIR)/* $(DEPDIR)/* $(GOAL)

tests:
	$(CC) $(CPPFLAGS) test/tester.cpp $(INC) $(LIB) -o bin/tester

info:
	$(CPP) $(CPPFLAGS) -dM -E - < /dev/null
